# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.1.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(640, 480)
        self.btn_ver = QPushButton(Form)
        self.btn_ver.setObjectName(u"btn_ver")
        self.btn_ver.setGeometry(QRect(140, 40, 75, 24))
        self.btn_list = QPushButton(Form)
        self.btn_list.setObjectName(u"btn_list")
        self.btn_list.setGeometry(QRect(140, 90, 75, 24))
        self.btn_spl = QPushButton(Form)
        self.btn_spl.setObjectName(u"btn_spl")
        self.btn_spl.setGeometry(QRect(140, 130, 75, 24))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 50, 101, 16))
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 90, 101, 16))
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 130, 131, 31))
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 180, 131, 31))
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 220, 131, 31))
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 260, 131, 31))
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 310, 81, 31))
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 360, 81, 21))
        self.btn_write = QPushButton(Form)
        self.btn_write.setObjectName(u"btn_write")
        self.btn_write.setGeometry(QRect(130, 180, 75, 24))
        self.btn_exec = QPushButton(Form)
        self.btn_exec.setObjectName(u"btn_exec")
        self.btn_exec.setGeometry(QRect(140, 230, 75, 24))
        self.btn_spiflash_info = QPushButton(Form)
        self.btn_spiflash_info.setObjectName(u"btn_spiflash_info")
        self.btn_spiflash_info.setGeometry(QRect(140, 270, 75, 24))
        self.btn_spiflash_read = QPushButton(Form)
        self.btn_spiflash_read.setObjectName(u"btn_spiflash_read")
        self.btn_spiflash_read.setGeometry(QRect(140, 310, 75, 24))
        self.btn_spiflash_write = QPushButton(Form)
        self.btn_spiflash_write.setObjectName(u"btn_spiflash_write")
        self.btn_spiflash_write.setGeometry(QRect(140, 350, 75, 24))
        self.lineEdit = QLineEdit(Form)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(250, 130, 231, 21))
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(510, 130, 75, 24))
        self.lineEdit_2 = QLineEdit(Form)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(230, 180, 71, 21))
        self.lineEdit_3 = QLineEdit(Form)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(310, 180, 231, 21))
        self.pushButton_2 = QPushButton(Form)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(550, 180, 75, 24))
        self.lineEdit_4 = QLineEdit(Form)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(240, 230, 71, 21))
        self.lineEdit_5 = QLineEdit(Form)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(230, 310, 71, 21))
        self.lineEdit_6 = QLineEdit(Form)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(310, 310, 71, 21))
        self.lineEdit_7 = QLineEdit(Form)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(390, 310, 131, 21))
        self.pushButton_3 = QPushButton(Form)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(540, 310, 75, 24))
        self.lineEdit_8 = QLineEdit(Form)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(230, 350, 71, 21))
        self.lineEdit_9 = QLineEdit(Form)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(390, 350, 131, 21))
        self.lineEdit_10 = QLineEdit(Form)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(310, 350, 71, 21))
        self.pushButton_4 = QPushButton(Form)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(540, 350, 75, 24))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.btn_ver.setText(QCoreApplication.translate("Form", u"\u70b9\u51fb", None))
        self.btn_list.setText(QCoreApplication.translate("Form", u"\u70b9\u51fb", None))
        self.btn_spl.setText(QCoreApplication.translate("Form", u"\u70b9\u51fb", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u67e5\u770b\u82af\u7247\u4fe1\u606f", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u5217\u51fa\u6240\u6709\u82af\u7247\u4fe1\u606f", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u52a0\u8f7d\u6267\u884cuboot\u7684spl", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u5199\u5165\u5185\u5b58\u6307\u5b9a\u4f4d\u7f6e", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u8c03\u7528\u6307\u5b9a\u5730\u5740\u51fd\u6570", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u663e\u793aspi-flash\u4fe1\u606f", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"\u8bfb\u53d6spi-flash", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"\u5199spi-flash", None))
        self.btn_write.setText(QCoreApplication.translate("Form", u"\u70b9\u51fb", None))
        self.btn_exec.setText(QCoreApplication.translate("Form", u"\u70b9\u51fb", None))
        self.btn_spiflash_info.setText(QCoreApplication.translate("Form", u"\u70b9\u51fb", None))
        self.btn_spiflash_read.setText(QCoreApplication.translate("Form", u"\u70b9\u51fb", None))
        self.btn_spiflash_write.setText(QCoreApplication.translate("Form", u"\u70b9\u51fb", None))
        self.lineEdit.setText(QCoreApplication.translate("Form", u"\u6587\u4ef6\u8def\u5f84", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.lineEdit_2.setText(QCoreApplication.translate("Form", u"\u5730\u5740", None))
        self.lineEdit_3.setText(QCoreApplication.translate("Form", u"\u6587\u4ef6\u8def\u5f84", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.lineEdit_4.setText(QCoreApplication.translate("Form", u"\u5730\u5740", None))
        self.lineEdit_5.setText(QCoreApplication.translate("Form", u"\u5730\u5740", None))
        self.lineEdit_6.setText(QCoreApplication.translate("Form", u"\u957f\u5ea6", None))
        self.lineEdit_7.setText(QCoreApplication.translate("Form", u"\u6587\u4ef6\u8def\u5f84", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
        self.lineEdit_8.setText(QCoreApplication.translate("Form", u"\u5730\u5740", None))
        self.lineEdit_9.setText(QCoreApplication.translate("Form", u"\u6587\u4ef6\u8def\u5f84", None))
        self.lineEdit_10.setText(QCoreApplication.translate("Form", u"\u957f\u5ea6", None))
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"\u9009\u62e9", None))
    # retranslateUi

